all:
	g++ -o mainCaso1 mainCaso1.cpp busqueda.cpp genera.cpp -std=c++11
	g++ -o mainCaso2 mainCaso2.cpp busqueda.cpp genera.cpp -std=c++11
	g++ -o mainCaso3 mainCaso3.cpp busqueda.cpp genera.cpp codificaciones.cpp -std=c++17
